#!/usr/bin/env python3

"""
Writes the scripts.rst file in ../src by running over the list of 
scripts in the directory ../../scripts.  There are some simple 
assumptions about the structure of the files that should be adhered to
or otherwise discussed for future development.

Things that MUST be adhered to:
1. All default execution must be guarded by if __name__ == "__main__" :
2. The argparse bit must be split off as a separate function named "set_parser()" that returns the built parser.
3. The "prog=<...>" must be set to the script name.
4. CURRENTLY subdirectories of scripts are not supported.
"""

import glob


# Get the list of command line tools to document
script_list = glob.glob('../../scripts/themispy_*[!~]')
print("Adding documentation for the following:")
print("  ",script_list)

# Open output file
out=open('scripts.rst.autogen','w')

# Output preamble info
out.write(".. WARNING: DO NOT EDIT THIS FILE. IT IS OVERWRITTEN DURING DOCUMENTATION CONSTRUCTION.  SEE /docs/scripts/write_script_docs.py FOR MORE INFORMATION ABOUT THIS FILE.\n\n") 
out.write(".. module:: scripts\n\n\n")

# Start looping over files:
for script in script_list :

    # Get the prog name:
    prog = script.replace('../../scripts/','')
    filename = '../scripts/'+prog
    
    out.write(prog+'\n')
    out.write('----------------------------------\n')
    out.write('.. argparse::\n')
    out.write('   :filename: %s\n'%filename)
    out.write('   :func: set_parser\n')
    out.write('   :prog: %s\n'%prog)
    out.write('   :nodefault:')
    out.write('\n\n\n')


out.close()

